package mocks

import "github.com/t11e/go-hydrantclient"
import "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Query provides a mock function with given fields: query, dataset
func (_m *Client) Query(query *hydrantclient.Query, dataset string) (*hydrantclient.ResultSet, error) {
	ret := _m.Called(query, dataset)

	var r0 *hydrantclient.ResultSet
	if rf, ok := ret.Get(0).(func(*hydrantclient.Query, string) *hydrantclient.ResultSet); ok {
		r0 = rf(query, dataset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hydrantclient.ResultSet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*hydrantclient.Query, string) error); ok {
		r1 = rf(query, dataset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
